version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: sample-app-web
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - "..:/app"
    stdin_open: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
  db:
    image: postgres
    container_name: sample-app-db
    ports:
      - "5432:5432"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'